sudo: required
services:
  - docker

before_install:
  - docker build -t marttp/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true marttp/react-test npm test

after_success:
  - docker build -t marttp/multi-client ./client
  - docker build -t marttp/multi-nginx ./nginx
  - docker build -t marttp/multi-server ./server
  - docker build -t marttp/multi-worker ./worker

  # Set env variable docker login data to travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take to Dockerhub
  - docker push marttp/multi-client
  - docker push marttp/multi-nginx
  - docker push marttp/multi-server
  - docker push marttp/multi-worker